# destination: ./_site
baseurl: /LIP/PLUME
auto:        true
# lsi:         false
server_port: 4000
pygments:    true
permalink:   date
markdown:    rdiscount
rdiscount:
    extensions: [smart]
# Prose.io
prose:
  siteurl: http://www.ens-lyon.fr/LIP/PLUME/
  rooturl: pages
  media: assets/img
  relativeLinks: http://www.ens-lyon.fr/LIP/PLUME/links.jsonp
  metadata:
    pages:
      - name: categories
        field:
          label: Categories
          element: select
          placeholder: Select a category
          options:
            - name: cat1
              value: cval1
            - name: cat2
              value: cval2
      - name: layout
        field:
          element: hidden
          value: post
      - name: title
        field:
          element: text
          label: Title
          value: ""
      - name: excerpt
        field:
          element: text
          label: Excerpt
          value: ""
      - name: author
        field:
          element: text
          label: Author
          value: Plume Webmaster
      - name: comments
        field:
          element: checkbox
          label: Comments Enabled
          value: true
      - name: tags
        field:
          element: text
          label: Tags
          value: ""
    "/":
      - name: title
        field:
          element: text
          label: Title
          value: ""
      - name: excerpt
        field:
          element: text
          value: ""
      - name: id
        field:
          element: text
          value: ""
      - name: layout
        field:
          element: select
          placeholder: Select a layout
          options:
            - name: Page
              value: page
            - name: Home
              value: home
            - name: Default
              value: default
            - name: Resume
              value: resume
