# destination: ./_site
baseurl: /Editeurs/paudebau.github.io
auto:        true
# lsi:         false
server_port: 4000
pygments:    true
permalink:   date
markdown:    rdiscount
rdiscount:
    extensions: [smart]
